project:
  type: website
  output-dir: docs

website:
  title: "Jinya Sakurai"
  page-navigation: true
  navbar:
    pinned: true
    right:
      - text: About me
        href: index.qmd#about
      - text: News
        href: index.qmd#news
      - text: Research
        href: index.qmd#research
      - text: Publications
        href: index.qmd#publications
      - text: Education
        href: index.qmd#education

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    css: styles.css
    include-after-body: effects.js
    toc: false
    smooth-scroll: true
    link-external-newwindow: true
