project:
  type: website
  output-dir: docs

website:
  title: "Jinya Sakurai"
  page-navigation: true
  navbar:
    pinned: true
    right:
      - text: About
        href: index.qmd#about
      - text: News
        href: index.qmd#news
      - text: Research
        href: index.qmd#research
      - text: Publications
        href: publications.qmd
      - text: Contact
        href: index.qmd#contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
    link-external-newwindow: true
